/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hasi.GetStockProfit;

import org.junit.Test;

import com.hasi.GetStockProfit.Application;

import static org.junit.Assert.*;

public class Application {

}
